#! /bin/sh

sxhkd &

source ~/.config

panel &

$HOME/.config/polybar/launch.sh

nitrogen --restore &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          50
bspc config bottom_padding       0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a URxvt state=floating rectangle=540x80+700+500
bspc rule -a Inkscape state=floating rectangle=1920x1000+0+75
bspc rule -a Surf state=tiled
